In [ ]:
#QUESTION 2

In [2]:
import numpy as np

In [ ]:
#Let the equations be
# 2x+3y-z=5
# x-5y+3z=7
# 3x+y+2z=4.


In [3]:
#co efficients
coefficients=np.array([[2,3,-1],[1,-5,3],[3,1,2]])
print(coefficients)

[[ 2  3 -1]
 [ 1 -5  3]
 [ 3  1  2]]


In [4]:
#Constants
constants=np.array([5,7,4])
print(constants)

[5 7 4]


In [11]:
solution = np.linalg.solve(coefficients,constants)
print(solution)

[ 4.66666667 -2.66666667 -3.66666667]
