In [5]:
#Question 1 
# (a)
import numpy as np
matrix = np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
print(matrix)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [6]:
#Transpose of the matrix
T = np.transpose(matrix)
print(T)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [8]:
#Determinant of the matrix
det_matrix=np.linalg.det(matrix)
print(det_matrix)

0.2299999999999999


In [9]:
#Decompose the matrix
decomposed_matrix=np.linalg.svd(matrix)
print(decomposed_matrix)

SVDResult(U=array([[-0.43721717,  0.85359707, -0.28321933],
       [-0.59931898, -0.51133314, -0.61591816],
       [-0.67056536, -0.09955128,  0.73514055]]), S=array([2.04100779, 0.82188052, 0.13711169]), Vh=array([[-0.43721717, -0.59931898, -0.67056536],
       [ 0.85359707, -0.51133314, -0.09955128],
       [-0.28321933, -0.61591816,  0.73514055]]))


In [11]:
#Transform the matrix
transformed_matrix=np.rot90(matrix)
print(transformed_matrix)

[[0.5 0.8 1. ]
 [0.2 1.  0.8]
 [1.  0.2 0.5]]
